#!/usr/bin/env bash
# Publish android-app/ to the standalone public GPLv3 repository.
#
# The Arena sandbox's GitHub token is scoped to this repository only, so it
# cannot create yt-convert-android for you. Run this once from a machine (or
# any shell) where `gh` is logged in as your own account.
#
#   bash scripts/publish-android-repo.sh
#
# It creates github.com/<owner>/yt-convert-android if missing, copies the
# android-app tree into a clean working directory, and pushes it as the
# initial commit on main. Re-running pushes an update commit instead.

set -euo pipefail

OWNER="${OWNER:-rahmanjimmy504-code}"
REPO="${REPO:-yt-convert-android}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/android-app"
WORK="${WORK:-${TMPDIR:-/tmp}/${REPO}-publish}"

if [ ! -d "$SRC" ]; then
  echo "error: $SRC not found — run this from the yt-convert checkout." >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "error: the GitHub CLI (gh) is required." >&2
  exit 1
fi

echo "==> Ensuring $OWNER/$REPO exists"
if gh repo view "$OWNER/$REPO" >/dev/null 2>&1; then
  echo "    already exists"
else
  gh repo create "$OWNER/$REPO" \
    --public \
    --description "GPLv3 Android companion for YT Convert — React, Vite, Tailwind, Capacitor and a native Kotlin extractor plugin." \
    --disable-wiki
  echo "    created"
fi

echo "==> Staging a clean copy in $WORK"
rm -rf "$WORK"
mkdir -p "$WORK"

# Copy everything except build output and dependencies. The Android project's
# generated assets are regenerated by `npx cap sync android`.
tar -C "$SRC" \
  --exclude='node_modules' \
  --exclude='dist' \
  --exclude='android/.gradle' \
  --exclude='android/build' \
  --exclude='android/app/build' \
  --exclude='android/app/src/main/assets/public' \
  --exclude='android/app/src/main/assets/capacitor.config.json' \
  --exclude='android/app/src/main/assets/capacitor.plugins.json' \
  --exclude='android/local.properties' \
  --exclude='*.apk' \
  --exclude='*.jks' \
  --exclude='*.keystore' \
  -cf - . | tar -C "$WORK" -xf -

cd "$WORK"
git init -q -b main
git add -A
git -c user.name="${GIT_AUTHOR_NAME:-$OWNER}" \
    -c user.email="${GIT_AUTHOR_EMAIL:-$OWNER@users.noreply.github.com}" \
    commit -q -m "YT Convert for Android: GPLv3 UI parity, Capacitor shell, empty Kotlin plugin, debug-APK workflow

Reproduces the YT Convert interface with React, Vite, Tailwind and Capacitor.
No server routes are included. The native YTExtractor plugin compiles and
reports that on-device extraction is not available yet, so the debug APK can
be installed and verified before download logic is added."

echo "==> Pushing to $OWNER/$REPO"
git remote add origin "https://github.com/$OWNER/$REPO.git"
git push -u origin main --force

echo
echo "Done. Next:"
echo "  1. https://github.com/$OWNER/$REPO/actions — wait for 'Debug APK' to finish"
echo "  2. Download the yt-convert-debug-<sha> artifact on your phone"
echo "  3. Unzip and install app-debug.apk"
